- bower.json
@AlbertoElias Can you merge and release this and o-dom asap pleas. ta
> More semver updates

- demos/checkboxes.html
- demos/global-errors.html
- demos/prefix-suffix.html
- demos/radios.html
- demos/section-errors.html
- demos/select-boxes.html
- demos/text-inputs.html
- demos/textareas.html
- origami.json
- src/scss/_mixins.scss
- src/scss/field-errors.scss
- src/scss/field-valid.scss
- src/scss/fields.scss
- src/scss/messages.scss
- src/scss/prefix-suffix.scss
- src/scss/radio-checkbox.scss
This should solve some of the issues raised in #81
/ping @Thurst-ft @jamesnicholls
> [V1] Add mixins to reproduce styles in silent mode

- README.md
- src/scss/_mixins.scss
> Unskin class: documentation and more agressive reset

- demos/real-life.html
> Fix build service dependencies for real-life demo

- demos/src/pa11y.mustache
- demos/src/select-boxes.mustache
- src/scss/base.scss
- src/scss/mixins/_select.scss
> Add support for "multi-select" select inputs

- designguidelines.md
Initial addition of design guidelines file to test new Build Service feature.
This new file will eventually expand to include adding demos in specific places amongst the documentation as well as images etc. once those features get added to the Registry.
> Add design guidelines file

- demos/src/checkboxes-long-text.mustache
- demos/src/messages.mustache
- demos/src/pa11y.mustache
- demos/src/prefix-suffix.mustache
- demos/src/select-boxes.mustache
- demos/src/text-inputs.mustache
- demos/src/textareas.mustache
- demos/src/wrappers.mustache
- src/scss/base.scss
- src/scss/message.scss
- src/scss/mixins/_common.scss
- src/scss/wrapper.scss
After comments from a product they need to support wide fields, this adds that support
> Add a full width (wide) modifier

- designguidelines.md
> Update design guidelines

- bower.json
- main.scss
- src/scss/_variables.scss
> Add o-normalise and square the corners

- demos/src/pa11y.mustache
- demos/src/select-boxes.mustache
- demos/src/text-inputs.mustache
- src/scss/_variables.scss
- src/scss/base.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_radio-checkbox.scss
Add back small inputs. 
Adds support for small text and select inputs. 
Closes #130
> Small fields

- src/scss/prefix-suffix.scss
> make buttons work in input fields

- src/scss/_color-use-cases.scss
> use teal-100 for focus rings

- src/scss/mixins/_common.scss
- src/scss/mixins/_select.scss
> Use arrow-down instead of arrows-up-down - Fixes #145

- README.md
- demos/src/checkbox-toggle.mustache
- demos/src/demo.scss
- origami.json
- src/js/forms.js
- src/scss/_variables.scss
- src/scss/base.scss
- src/scss/mixins/_radio-checkbox.scss
- test/forms.test.js
Add checkbox toggles.
```
<form data-o-component="o-forms">
<div class="o-forms__checkbox-toggle">
<input data-o-form-toggle type="checkbox">
</div>
</form>
```
They fire and event `oForms.toggled` when clicked.
> Checkbox toggle

- circle.yml
- demos/src/checkbox-toggle.mustache
- demos/src/checkboxes.mustache
- demos/src/messages.mustache
- demos/src/pa11y.mustache
- demos/src/radios.mustache
- demos/src/select-boxes.mustache
- demos/src/suffix.mustache
- demos/src/textareas.mustache
- demos/src/wrappers.mustache
Mostly connecting labels with inputs. Also changing `fieldset` back to `div` for demos which are not true fieldsets.
`obt test` to verify
> Update demos for pa11y checks.

- README.md
- demos/src/radios.mustache
- demos/src/sections.mustache
This aims to document `o-forms` with migration guide.
> Update the readme for v5

- README.md
- demos/src/radios-button-styling.mustache
- origami.json
- src/scss/_color-use-cases.scss
- src/scss/base.scss
- src/scss/mixins/_radio-checkbox.scss
A button set allowing either one selected by default, or none.
Design from @draysonandstock
> Radios styled as button set

- demos/src/radios.mustache
- src/scss/mixins/_radio-checkbox.scss
Demo updates not relevant to focus state change. Updates radio button names.
> Restore radio and checkbox focus state + update demo

- demos/src/radios-button-styling.mustache
- origami.json
- src/scss/_color-use-cases.scss
- src/scss/mixins/_radio-checkbox.scss
> Styled radio buttons - allow +/- choice; spaced styling

- src/scss/mixins/_common.scss
Addresses: https://github.com/Financial-Times/o-forms/issues/195
before:
after:
> Update validated input focus states.

- demos/src/status.mustache
The JS is correct but the demos are wrong.
> arial-live should be set to "assertive" rather than "true" in the demos.

- demos/src/inline-controls.mustache
- src/scss/_variables.scss
- src/scss/mixins/_common.scss
> Increase bottom margin of controls to allow for status.

- bower.json
- demos/src/dates.mustache
- demos/src/text-inputs.mustache
- demos/src/validation.mustache
- main.scss
- origami.json
- src/scss/_variables.scss
- src/scss/base.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_date.scss
- src/scss/mixins/_labels.scss
- src/scss/mixins/_radio-checkbox.scss
- src/scss/mixins/sections.scss
- src/scss/mixins/suffix.scss
- Add date capture input group.
- Also remove some private typography variables.
Discussed this design in the uxd surgery with Mark H and Simon C.
> Add date capture input group.

- bower.json
- src/scss/base.scss
This allows all components to be intalled together at their latest versions ^.^
> Update o-loading to version 3 

- bower.json
- src/scss/base.scss
Reverts Financial-Times/o-forms#241
> Revert "Revert "Update o-loading to version 3 ""

- .circleci/config.yml
- README.md
Depends on https://github.com/Financial-Times/o-ft-affiliate-ribbon/pull/22
> Update circleci config to use occ for publishing

- README.md
None of the examples in the docs currently work 🙈
> Switch require to import in the docs

- demos/src/demo.js
- src/js/forms.js
- test/forms.test.js
- test/input.test.js
- test/state.test.js
Removes CJS traces, adds the getDataAttributes that all other components have.
Closes #246
> V7: ESModules

- src/scss/_radio-round.scss
See https://github.com/Financial-Times/n-feedback/pull/68#discussion_r291969904
> Do not assume a paper background for radios.

- bower.json
- main.scss
- src/scss/_pseudo-radio-link.scss
- src/scss/shared/_control-inputs.scss
- src/scss/shared/_variables.scss
o-spacing functions replace:
- oTypographyMargin
- oTypographyPadding
- oTypographySpacingSize
Although this introduced a new dependency, o-spacing is new and should not be considered breaking.
> Introduce o-spacing.

- MIGRATION.md
- src/js/forms.js
> Remove the deprecated setState interface

- README.md
- bower.json
- demos/src/demo.scss
- src/scss/_checkbox.scss
- src/scss/_radio-box.scss
- src/scss/_radio-round.scss
- src/scss/_select.scss
- src/scss/_toggle.scss
- src/scss/modifiers/_custom.scss
- src/scss/modifiers/_state.scss
- src/scss/shared/_base.scss
- src/scss/shared/_brand.scss
- src/scss/shared/_control-inputs.scss
- src/scss/shared/_error-summary.scss
- src/scss/shared/_single-inputs.scss
- src/scss/shared/_validity.scss
**ready for review but do not merge until whitelabel crimson and jade colours are restored**
> Upgrade dependencies to the latest beta

- demos/src/data/pa11y.json
- demos/src/data/select.json
- demos/src/data/text-input.json
- demos/src/interactive.mustache
- test/helpers/fixtures.js
They weren't using the secondary modifier.
> Fix buttons in the demos

- README.md
- demos/src/demo.scss
- src/scss/_pseudo-radio-link.scss
- src/scss/_radio-box.scss
- src/scss/modifiers/_custom.scss
i.e. so the border may be white on a claret background
> Allow radio box border colour customisation

- demos/src/data/checkboxes.json
[Thanks Keith!](https://github.com/Financial-Times/origami-component-converter/pull/35)
> Fix typo in demo description

- test/forms.test.js
- test/helpers/fixtures.js
Turns out this is not a problem,
I thought it might have been,
but now we have tests to confirm it.
> Test one form does not validate on submit of a different form.

- README.md
- demos/src/data/date.json
- demos/src/data/pa11y.json
- demos/src/interactive.mustache
- demos/src/multiple-input-field.mustache
- src/scss/_date.scss
- test/helpers/fixtures.js
Introduces new class selectors so we can change validation
patterns independently of input style.
Fixes: https://github.com/Financial-Times/o-forms/issues/317
> Improve day input regex pattern for slightly better validation.

- README.md
- origami.json
- src/js/error-summary.js
- src/scss/shared/_error-summary.scss
For users who do not use o-forms JavaScript.
> Allow a declaritive error summary.

- src/scss/_radio-box.scss
> Improve radio box input given long labels
