Financial-Times/o-forms

- demos/checkboxes.html
- demos/global-errors.html
- demos/prefix-suffix.html
- demos/radios.html
- demos/real-life.html
- demos/section-errors.html
- demos/select-boxes.html
- demos/src/config.json
- demos/src/demo.scss
- demos/src/real-life.mustache
- demos/text-inputs.html
- demos/textareas.html
- src/scss/_color-use-cases.scss
- src/scss/_mixins.scss
- src/scss/field-errors.scss
- src/scss/radio-checkbox.scss
- Adds a real life example (code taken from the subscription form)
- Adds smooth animations on focus states
- Improve focus states (now noticeable even on fields in error)
This PR adds an inner focus ring on fields to differentiate them better from non-focused fields.
Low contrast between checkbox and background:
No focus indicator on error fields:
> [V1] Real life example and states improvements

- demos/checkboxes.html
- demos/radios.html
- demos/src/checkboxes.mustache
- demos/src/radios.mustache
- src/scss/_color-use-cases.scss
- src/scss/_mixins.scss
- src/scss/radio-checkbox.scss
- New disabled states for checkboxes and radio buttons (they deserve it, too)
- Disabled inputs don't look like buttons anymore (Fixes #73)
Text: default field background (30%) + default text (70%)
Border: default field background (50%) + default border (50%)
Background: default field background (15%) + default border (85%)
**Q: Why not RGBA (transparent colors)?**
A: because plain colours are compatible with older browsers.
**Q: Why mixing colours instead of creating new use cases?**
A: to avoid having to override lots of use cases in their code if a product wants to change the color scheme
Opacity simply set to 40% because it's simpler than changing colours of checked/unchecked states in combination with the disabled state.
> Disabled states - fixes #73

- .gitignore
- README.md
- demos/src/demo.js
- demos/src/pa11y.mustache
- demos/src/text-inputs.mustache
- demos/src/validation.mustache
- karma.conf.js
- main.js
- origami.json
- package.json
- src/js/forms.js
- src/scss/message.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_radio-checkbox.scss
- src/scss/mixins/_select.scss
- src/scss/prefix-suffix.scss
- src/scss/unskin.scss
- src/scss/wrapper.scss
- test/forms.test.js
- test/helpers/fixtures.js
- test/origami.test.js
Adds the ability to validate forms based on the Constraint Validation API in browsers, applying the appropriate `o-forms` classes when an error has occurred and preventing Safari from submitting a form if errors are present (other browsers do this as standard).
Also updates readme to fit Origami structure.
> Add form validation 

- README.md
- bower.json
- demos/src/demo.scss
- main.scss
- origami.json
- src/scss/_color-use-cases.scss
- src/scss/_variables.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_labels.scss
- src/scss/mixins/_radio-checkbox.scss
- src/scss/mixins/_select.scss
- src/scss/prefix-suffix.scss
- src/scss/unskin.scss
I'm still working on the migration guide, opening pull request to get feedback on what has been done.
Old:
New:
> Implemented new design using latest o-colors and o-typography

- origami.json
Demos for o-forms are not being displayed correctly due to a bower conflict in their dependencies -- https://www.ft.com/__origami/service/build/v2/demos/o-forms@4.0.0/text-inputs
Updating o-buttons to the latest version should fix this issue.
> use latest version of buttons to avoid a conflict

- src/scss/mixins/_common.scss
- src/scss/mixins/_select.scss
The down arrow indicating a drop-down menu inside an input field was invisible on IE11, as raised by this issue: https://github.com/Financial-Times/o-forms/issues/143
This fix makes it visible on IE and other browsers so it appears as it should:
> Fix bug in ie11 that hid icons in input fields

- src/scss/mixins/_radio-checkbox.scss
I mistakenly removed these here (released in `o-forms@4.1.0`) 😞:
https://github.com/Financial-Times/o-forms/pull/155/files
Causing this issue:
https://github.com/Financial-Times/o-forms/issues/161
> Reinstate removed o-forms__prefix and o-forms__suffix styles.

- src/scss/suffix.scss
Fixes a suffix bug in IE9 which effected the select dropdown and spacing... this PR also removes some -- what appears to be -- redundant css `border-top-left-radius`.
The workaround for the spacing issue, making any child of the suffix display as a table cell, is gross. The problem occurs in IE9 if the child has no explicit width and `box-sizing: border-box`. The extra space leaves enough room for the child to be displayed as if it were not set to `box-sizing: border-box`. 🤔 
before
after
> Fix IE9 suffix bug

- src/scss/base.scss
potentially breaking change but looks like most origami users are already doing this inside their own css
> hide errortext until error modifier is used on the form

- src/scss/mixins/_common.scss
James spotted an alignment issue. The text within a form input is not quite centred. Oddly (I don't know why) this can be avoided by not setting a height. Instead we will rely on padding to produce the correct height.
Wait for it...
> Input text vertical spacing

- src/scss/mixins/_common.scss
This https://github.com/Financial-Times/o-forms/pull/181 negatively impacted select box height. Rather than restore height we can use min-height to defend against this.
Before
After
> Correct select input height

- README.md
- demos/src/radios-button-styling.mustache
- src/scss/base.scss
- src/scss/mixins/_radio-checkbox.scss
Builds on https://github.com/Financial-Times/o-forms/pull/183/files
- Adds the ability to optionally output styled radio buttons with `oFormsRadioButtonsStyledFeature` rather than include them in base features.
- Uses `o-forms__group` for margins consistent with standard checkboxes/radios.
- Adds `o-forms__group--inline-together`, uses floats and grids for visually improved browser support.
- Renames `o-forms__radio-buttons__button` `o-forms__radio-button`
- Adds to readme.
> Update radios button styled.

- README.md
- demos/src/checkboxes.mustache
- demos/src/pa11y.mustache
- demos/src/sections.mustache
- demos/src/suffix.mustache
- demos/src/text-inputs.mustache
- demos/src/textareas.mustache
- demos/src/validation.mustache
- test/helpers/fixtures.js
Request by @draysonandstock. Placeholders may cause confusion, especially in pre-filled form contexts. We would rather keep hints outside the input as addition info. 
https://financialtimes.slack.com/archives/C2LMEKC6S/p1518602515000541
https://financialtimes.slack.com/files/U58PJHY78/F987TTRPS/screen_shot_2018-02-14_at_10.12.34.png
> Remove placeholders from demos.

- src/scss/base.scss
If a custom class is used instead of o-forms, it's not currently being passed through by the top-level mixins.
> Pass root classname to nested mixins

- src/scss/mixins/_common.scss
Fields will only show as valid/invalid if they are not disabled.
Disabled fields with validator classes:
> Do not show validation styles if input is disabled.

- README.md
- demos/src/checkboxes.mustache
- demos/src/demo.scss
- demos/src/inline.mustache
- demos/src/pa11y.mustache
- demos/src/radios-button-styling.mustache
- demos/src/radios.mustache
- demos/src/select-boxes.mustache
- demos/src/text-inputs.mustache
- demos/src/textareas.mustache
- demos/src/toggle.mustache
- origami.json
- src/scss/_variables.scss
- src/scss/base.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_labels.scss
- src/scss/mixins/_radio-checkbox.scss
- src/scss/mixins/suffix.scss
1. Adds inline forms (IE9 falls back to stacked).
2. Updates styled radio button error state.
3. Reduces styled radio button padding. 
4. Removes white background from radio buttons.
1. There are some mad selectors and specificity here -- feedback welcome. Inputs/input groups have unique margins between their label/legend, i.e. a group of checkboxes or radios are closer to their legend than styled radio buttons or text inputs are. This means the inputs/input groups own the margin (margin-top) rather than the labels/legends (margin-bottom). Input groups such as checkboxes may also have negative margins which enable their children to be inline within a stacked form. As the margins are unique and sometimes negative to support inline child elements it becomes problematic to remove the …
> Inline forms and other visual improvements.

- src/scss/_variables.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_radio-checkbox.scss
- src/scss/mixins/sections.scss
- Checkbox/radio groups now have a 12px margin from their legend (up from 8px).
- Checkboxes/radios within a group now have a 16px margin between one another (down drom 20px).
I've also renamed some variables to avoid confusion. Unfortunately we have a class `o-forms__group` which does not relate to `$_o-forms-group-spacing`.
`$_o-forms-group-spacing` is the space between instances of `o-forms` or [form sections](https://www.ft.com/__origami/service/build/v2/demos/o-forms@5.5.1/sections). I've renamed `$_o-forms-group-spacing` to `$_o-forms-section-spacing` and `$_o-forms-inline-group-spacing` to `$_o-forms-inline-section-spacing`.
before
after
> Update vertical spacing.

- README.md
- demos/src/inline-controls.mustache
- src/js/forms.js
- src/scss/base.scss
- src/scss/mixins/_common.scss
- test/forms.test.js
- test/helpers/fixtures.js
- Add a method to set form input status.
- Visually hide icon only statuses so screenreaders can read them.
- Set inactive statuses to `display: none` when not inline so they take no space
> Form Status JS

- README.md
- bower.json
- demos/src/inline-controls.mustache
- demos/src/status.mustache
- main.scss
- origami.json
- src/js/forms.js
- src/scss/_variables.scss
- src/scss/base.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_labels.scss
- src/scss/mixins/_radio-checkbox.scss
- test/forms.test.js
- test/helpers/fixtures.js
Adds the concept of a form status including "saving" and "saved".
Also works with inline controls:
> Add form status

- demos/src/status.mustache
- src/scss/base.scss
- src/scss/mixins/_common.scss
So that setting a status does not push content down.
See issue: https://github.com/Financial-Times/o-forms/issues/219
> Make status sit within o-forms bottom margin.

- README.md
- demos/src/anchor-radios-button-styling.mustache
- demos/src/custom.mustache
- demos/src/demo.scss
- origami.json
- src/scss/_variables.scss
- src/scss/mixins/_radio-checkbox.scss
**Changes**
- Updated styled radio buttons to be smaller with less padding, intentionally closer to `o-buttons`.
- Add the ability to achieve the look of styled radio buttons but with anchor tags.
- Add the ability to customise the color of styled radio buttons and add an icon.
**Why**
To improve the MyFT page, replacing a group of `o-buttons`.
Current:
New (wireframe, no color):
**How**
Example of a custom theme and icon:
```scss
$_o-forms-demo-theme: (
'checked-background': 'claret-50',
'border': 'black-30'
);
.o-forms__radio-button--custom-theme {
@include oFormsRadioButtonsStyledTheme($theme: $_o-forms-demo-theme);
}
.o-forms__radio-button--custom-list-icon {
@include oFormsRadioButtonsStyledIcon($icon-name: 'list', $theme: $_o-forms-demo-theme);
} …
```
> Update styled radio buttons.

- demos/src/demo.scss
- src/scss/_variables.scss
- src/scss/base.scss
- src/scss/mixins/_common.scss
- src/scss/mixins/_labels.scss
- src/scss/mixins/_radio-checkbox.scss
- src/scss/mixins/sections.scss
- src/scss/mixins/suffix.scss
Uses `o-typography` to output font-family and size rather than inherit it.
These changes support custom fonts and custom font scales:
https://github.com/Financial-Times/o-typography/pull/166
This update means form elements such as labels use the line height from our typographic scale rather than the browser default line-height. The impact of this is slightly larger spacing / slightly taller form elements as shown below.
Old / New
> Set font using o-typography.

- src/scss/mixins/_radio-checkbox.scss
Before
After
This visual bug was introduced here: https://github.com/Financial-Times/o-forms/pull/230
> Correct right aligned checkbox checked state.

- MIGRATION.md
- README.md
- main.scss
- src/scss/_text-input.scss
_(review with whitespace removed)_
So input types such as `email` and `tel` may be styled as text fields,
style any `input` which is the child of `.o-forms-input--text` as a
text input.
This means we don't have to provide individual selectors for a large
and ever changing set of input types.
See issue: https://github.com/Financial-Times/o-forms/issues/272
> Allow any text-like input (e.g. email) to be styled as a text input.

- demos/src/interactive.mustache
- src/js/error-summary.js
- test/helpers/fixtures.js
E.g. a hidden input.
Review with whitespace hidden.
Fixes: https://github.com/Financial-Times/o-forms/issues/276
> Handle inputs with an `undefined` `valid` getter.

- src/scss/_radio-round.scss
- An element with `visibility: hidden` does not recieve tab focus, 
but it was added to [our radio buttons here](https://github.com/Financial-Times/o-forms/pull/271)  😱 
- Also the focus state should be applied to the radio circle rather than the input itself.
> Correct radio button focus state.

- README.md
- demos/src/data/radio-box.json
- demos/src/interactive.js
- demos/src/multiple-input-field.mustache
- src/js/forms.js
- src/js/state.js
- src/scss/modifiers/_state.scss
- test/forms.test.js
- test/state.test.js
Relates to the saving/saved states in this demo: https://www.ft.com/__origami/service/build/v2/demos/o-forms@7.0.11/radio-box?brand=master
The classes `o-forms-input--saving` and `o-forms-input--saved`
add an icon and "Saving" or "Saved" copy to an element
`<span class="o-forms-input__state"></span>`.
These modifier classes and state element may be set using the
`setState` JS method, but may also be added manually.
As the `o-forms-input--saving` and `o-forms-input--saved` classes
add copy using pseudo elements the label of the state is not
customisable. E.g. "Saved" can't be changed to "Sent" where it
makes sense for the ui, and also the copy can't be localised.
Instead of including the copy for `saving` and `saved` states via
CSS, this PR proposes adding the copy via HTML. This may be …
> Allow the label of box radio buttons to be customised.

- demos/src/data/checkboxes.json
- src/scss/shared/_control-inputs.scss
When using a checkbox that has extra content (i.e. more than one `<span class="o-forms-input__label">`), there are two issues:
1) Clicking on either the label or the checkbox does not visibly check the checkbox. The field will be marked as checked in the DOM, but it just won't be visually apparent. This issue can be seen on the [Checkboxes demo for `o-forms` version `8.0.0`](https://registry.origami.ft.com/components/o-forms@8.0.0#demo-checkboxes) under "Checkboxes with extra content."
2) When disabled, only the first label for the checkbox would have the disabled styling applied. Also, the checkbox would not have the disabled styling.
I've only checked in Chrome and Firefox, but the issue occurs in both.
This is happening because each bit of content in the label has its own checkbox …
> Fix checked and disabled styles on checkboxes with extra content.

- src/scss/modifiers/_custom.scss
Also make the `o-forms-input__link--current` more specific.
Source order seems to be behind the icon appearing white on myft:
> Output custom form icon base styles only once.

- demos/src/data/radio-box.json
- demos/src/multiple-input-field.mustache
- src/scss/_radio-box.scss
- src/scss/shared/_validity.scss
When a label and input are inline, with label to the left and
input to the right, the state/error element is positioned on
the right under the input. If the label is long the status/error
message is pushed down away from the input due to absolute
positioning against their shared container.
Absolute positioning is used with a negative bottom value so the
state does not push content down the page when added dynamically.
The state sits within the fields margin instead. We can use
relative positioning and a negative margin instead. This keeps
the state close to the input when the label becomes long, but also
allows the state to avoid pushing other page content down by
negating the containers margin.
Relates to: #304
(Also fix "vertical centered inline radio box" demo.)
> Position state and error elements against inputs when labels are long.

- src/scss/_checkbox.scss
We recreate checkboxes with pseudo elements so hide the original
inputs visually.
Relates to https://github.com/Financial-Times/o-forms/issues/285
> Hide checkbox inputs.

- README.md
- demos/src/interactive.mustache
- src/js/error-summary.js
- src/js/forms.js
- test/forms.test.js
Warn in the console that the error summary cannot link to an input
with no id. This is better than not showing the user the error
in the summary at all. I considered generating an id but thought
it may risk collisions, or users attempting to hang logic from
dynamic ids which may change.
Also warn in the console if the error summary is enabled but an
invalid input does not have a field title to show in the error
summary. For example, using the label of a single checkbox
"I accept these terms." would not make sense in an error summary;
the developer should add a field title like "terms and conditions"
if they would also like to use the error summary with such an input.
> Show invalid inputs with missing ids in the error summary.

- src/js/forms.js
Upon re-submitting a form with invalid elements that is already showing a summary, the replacement of the previous summary wasn't updating the DOM reference. This lead to an error when attempting to replace the summary as the stored reference was no longer within the DOM tree. This meant we would receive:
```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
```
> fix: update form.summary with new element

- src/scss/shared/_single-inputs.scss
Small fix to prevent the inlining of flex children of a `o-forms-input--suffix` parent. See example below:
> Prevent errors inlining on inputs with a suffix element

- origami.json
These polyfills are already required by o-forms (so this isn't
a breaking change). As our users are already including these
polyfills I don't think we have to release a patch that removes
these features -- but they should be documented for the future.
> Document other required polyfills.

- src/scss/_select.scss
>If you only set one dimension using background-size and the other
>to auto, IE will choose the aspect ratio of the element rather
>than the intrinsic dimensions of the SVG graphic.
https://thatemil.com/blog/2015/03/15/sizing-svg-background-images-in-internet-explorer/
Fixes: https://github.com/Financial-Times/o-forms/issues/318
> Fix select input arrow position in IE11

- src/scss/shared/_base.scss
E.g. we do not want a drop shadow or border radius in mobile Safari
Before 😱:
After:
> Remove default browser styles.

- src/scss/_toggle.scss
Default browser styles were removed in the last commit but
o-forms toggles relied on hidden checkbox dimensions for
layout.
before/after
> Correct toggle spacing so the label is not obscured.

- src/scss/shared/_single-inputs.scss
> Ensure Safari uses the correct text colour for disabled inputs.

- test/forms.test.js
- test/input.test.js
- test/state.test.js
Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.
> Stop using magic webpack imports

- src/scss/shared/_single-inputs.scss
Allow form inputs with a suffix to shrink fully, regardless of the
input `size` attribute.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#htmlattrdefsize
> Set `min-width: 0` for inputs with a suffix.

- README.md
- src/js/error-summary.js
- test/forms.test.js
`appendChild` returns the appended child, not the parent. This
caused a bug where anchor tags were being placed within a `ul`
unordered list element of errors.
> Place error summary items within an `li` list element.

- src/scss/shared/_single-inputs.scss
In iOS Safari they were displaying with an opacity of 0.4. Fixes https://github.com/Financial-Times/o-forms/issues/347
> Make sure disabled text inputs have an opacity of 1.

- src/scss/_checkbox.scss
- src/scss/_radio-round.scss
- src/scss/shared/_control-inputs.scss
this should fix these:
https://financialtimes.atlassian.net/browse/NOPS-235
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1108&projectKey=ACC&modal=detail&selectedIssue=ACC-423 
and this https://github.com/Financial-Times/n-feedback/pull/88 
tested in:
Dragon on IE11 on Windows 10
Firefox on Linux
hopefully a kind robot can show us some visual regression tests from other browsers so we know we haven't made anything worse?
Also worth testing it has the same screenreader experience as the previous version
```
npm i -g origami-build-tools
git clone git@github.com:financial-times/o-forms
cd o-forms
obt install
obt dev
```
and try out http://localhost:8999/checkboxes and http://localhost:8999/radio-round
> Hide native radios and checkboxes while leaving them accessible to dragons

- src/scss/_radio-box.scss
following on from this: https://github.com/Financial-Times/o-forms/pull/352
@taraojo has pointed out that the `_oFormsControlsBase` mixin isn't used in the box-styled radio inputs!
i've added it here directly, but maybe we should also open an issue about getting the box-styled ones to actually use that mixin? because as @taraojo also points out, the comment on the mixin actually mentions box-style radios
> Also fix the inputs on the radio boxes

- demos/src/interactive.js
- main.js
- src/js/forms.js
- test/forms.test.js
- test/input.test.js
- test/state.test.js
relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing
> add extension to relative imports to make the code work directly in a browser

- demos/src/interactive-suffix.mustache
- origami.json
- src/scss/shared/_validity.scss
Fixes: https://github.com/Financial-Times/o-forms/issues/303
[`:valid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:valid) is targetting `button` since it is a form element.
Ideally I think we'd use a class here BEM style rather than exclude specific elements.
> Do not style suffix buttons based on validity.

- demos/src/demo.scss
- demos/src/inverse-form-whitelabel.mustache
- demos/src/inverse.scss
- origami.json
- src/js/error-summary.js
- src/scss/modifiers/_inverse.scss
- src/scss/shared/_brand.scss
Currently the demo for inverse fails for whitelabel as it is using `slate` colour which does not exist in the whitelabel colour palette. I've switched to a hardcoded value of `slate` to make it work.
This also updates the error states in whitelabel's inverse mode to match the new design used in internal and master brand
> Add better error styles for whitelabel brand in inverse mode

- src/scss/_radio-box.scss
- src/scss/_radio-round.scss
- src/scss/shared/_brand.scss
Some users of internal tools take our radio buttons to be disabled
when placed on a `slate-white-15` background. This makes radio
buttons (round and box) always `white` for the internal brand.
It’ll continue to be transparent for the master brand, for use on
paper/white pages.
Closes: https://github.com/Financial-Times/o-forms/issues/389
Discussion: https://financialtimes.slack.com/archives/C01481FKWA2/p1614769119021000
before/after round radios
before/after box radios
before/after master brand, no changes
> Add a white background to internal brand radio inputs.

- src/scss/_radio-box.scss
- src/scss/shared/_control-inputs.scss
By default box style radio buttons maintain a single line of copy and boxes 
wrap, maintaining the single line of copy, as a last resort to prevent 
overflow. The wrapping behaviour is maintained here but this commit 
makes box style radio buttons more flexible to allow for taller, 
multi-line radio buttons.
before/after with non-selected box hovered:
Excess white-space is removed incidentally as part of this change
which allows radio-box specific error message styles to be removed.
Elements below a box style radio button, such as subsequent input,
now appear closer — consistent with the spacing between other form
elements.
before/after
before/after
These changes came about for the payments page of ft.com, where box
inputs are being used more like tabs to alter inputs later in the
form. …
> Allow multi-line box-style radio button copy, making them taller.

- README.md
- bower.json
- demos/src/data/file-input.json
- demos/src/data/pa11y.json
- demos/src/demo.scss
- demos/src/file-input-field.mustache
- demos/src/inverse-form.mustache
- main.scss
- origami.json
- src/scss/_file-input.scss
- src/scss/main.scss
- src/scss/modifiers/_inverse.scss
Resolves https://github.com/Financial-Times/o-forms/issues/199
You can view the demos here: https://o-forms-files-nw7lggciez3va1gz.herokuapp.com/
> Add styling for file inputs using the new `::file-selector-button` pseudo-element

- src/scss/shared/_brand.scss
The current colour contrast is 3.71
The proposed colour, which is the same as master brand, gives a contrast of 5.45 - which exceeds the contrast requirements
I found this during the origami 2.0 component migration
> update colour for valid input modifier to comply with contrast requirements
